### ISSUE TITLE
"Firefox Can’t Open This Page" error

### ISSUE THREAD

**Issue by tabtomi8** [IKavanagh/BingChatInFirefox#8]
When I try to use Copilot in the sidebar, this error appears.

> Firefox Can’t Open This Page
> To protect your security, www.bing.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.
> [Learn more…](https://support.mozilla.org/1/firefox/125.0/WINNT/en-US/xframe-neterror-page)

> ![Képernyőkép 2024-04-26 130333](https://github.com/IKavanagh/BingChatInFirefox/assets/59199402/01c24fd0-38a6-45cf-952d-6a1796c3a940)

**Comment by IKavanagh** [comment]
I've stopped using the add-on since Microsoft moved to Copilot instead of Bing Chat and opened it up to Firefox users normally. Microsoft are now instructing Firefox not to allow it to display Bing Chat in the sidebar. Any attempts to override this would be identified as [Clickjacking](https://en.wikipedia.org/wiki/Clickjacking) which Firefox wouldn't allow.
